### ISSUE TITLE
Problem mit tinauer/main.c

### ISSUE THREAD

**Issue by ManfredSteiner** [HTLMechatronics/project9ahmea#2]
@tinrom12, schau dir das mal an

**Comment by tinrom12** [comment]
Sehr geehrter Herr Prof. Steiner,
ich werde mich darum kümmern.
Mit freundlichen Grüßen,
Robert Tinauer

**Comment by stastm12** [comment]
Good guy Robert!

**Comment by ManfredSteiner** [comment]
Aber rasch
